### ISSUE TITLE
Unable to install globally

### ISSUE THREAD

**Issue by shaunstanislaus** [sindresorhus/create-dmg#2]
```bash
shaunstanislaus@Master:~ $ npm i -g create-dmg
/usr/local/bin/create-dmg -> /usr/local/lib/node_modules/create-dmg/cli.js

> fs-xattr@0.1.15 install /usr/local/lib/node_modules/create-dmg/node_modules/fs-xattr
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/shaunstanislaus/.pyenv/shims/python2.7 -c import platform; print(platform.python_version());
gyp ERR! stack /Users/shaunstanislaus/.pyenv/shims/python2.7: line 21: /usr/local/Cellar/pyenv/1.0.8/libexec/pyenv: No such file or directory
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:205:12)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:191:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:513:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/create-dmg/node_modules/fs-xattr
gyp ERR! node -v v7.7.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
/usr/local/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-xattr@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-xattr@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fs-xattr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fs-xattr
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shaunstanislaus/.npm/_logs/2017-03-28T23_58_02_594Z-debug.log
```

**Comment by sindresorhus** [comment]
The error is coming from installing the `fs-xattr` dependency. Move this issue over there: https://github.com/LinusU/fs-xattr/issues
