### ISSUE TITLE
Unable to create dmg

### ISSUE THREAD

**Issue by cgtyky** [sindresorhus/create-dmg#3]
MacBook-Air-2:~ XXXXX$ create-dmg 'TinkerTool.app'
fs.js:583
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/xxxxx/TinkerTool.app/Contents/Info.plist'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-dmg/cli.js:30:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
MacBook-Air-2:~ XXXXX$

**Comment by sindresorhus** [comment]
That means the file doesn't exist. Make sure you used the correct path.
