### ISSUE TITLE
create-dmg fails on OSX Catalina

### ISSUE THREAD

**Issue by julioasotodv** [sindresorhus/create-dmg#53]
Hi!

Apparently, `create-dmg` does not work in the lastest release of OSX.

Using `"create-dmg=5.1.0"`, the executable fails in OSX 10.15.4:

```sh
create-dmg --help
```

Returns the following traceback:

```
internal/modules/cjs/loader.js:1173
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/myuser/Downloads/myapp/node_modules/macos-alias/build/Release/volume.node, 1): Symbol not found: _kCFURLVolumeNameKey
  Referenced from: /Users/myuser/Downloads/myapp/node_modules/macos-alias/build/Release/volume.node
  Expected in: flat namespace
 in /Users/myuser/Downloads/myapp/node_modules/macos-alias/build/Release/volume.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/myuser/Downloads/myapp/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
```

Thank you!

**Comment by sindresorhus** [comment]
That error is coming from a sub-dependency. It's a native addon, so you need to reinstall it if you upgraded your OS since installing it. If that's not the case, open an issue on that package instead.
