### ISSUE TITLE
Cannot find module '../build/Release/volume.node'

### ISSUE THREAD

**Issue by guoxiucai** [sindresorhus/create-dmg#6]
when I execute "create-dmg --help", error happen, can you  tell me why.
I am a newer to node.js, thanks~

----------------------
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/volume.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-dmg/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by sindresorhus** [comment]
Make sure you're on a recent Node.js and macOS version. The error is coming from https://github.com/LinusU/node-alias, so that would be the place to open an issue.

**Comment by r-thomson** [comment]
For anyone running across this in the future, I was having this problem because I have install scripts disabled. Here is the solution that worked for me:

```
npm install -g create-dmg --ignore-scripts=false
```
