### ISSUE TITLE
TypeError: util.isDate is not a function

### ISSUE THREAD

**Issue by hyrulelinks** [sindresorhus/create-dmg#93]
```
⠏ Making hidden background folder/opt/homebrew/lib/node_modules/create-dmg/node_modules/macos-alias/lib/encode.js:8
  if (util.isDate(value) === false) {
           ^

TypeError: util.isDate is not a function
    at appleDate (/opt/homebrew/lib/node_modules/create-dmg/node_modules/macos-alias/lib/encode.js:8:12)
    at exports (/opt/homebrew/lib/node_modules/create-dmg/node_modules/macos-alias/lib/encode.js:44:23)
    at Object.exports [as create] (/opt/homebrew/lib/node_modules/create-dmg/node_modules/macos-alias/lib/create.js:145:10)
    at Helper.write (/opt/homebrew/lib/node_modules/create-dmg/node_modules/ds-store/index.js:50:22)
    at Object.fn (/opt/homebrew/lib/node_modules/create-dmg/node_modules/appdmg/lib/appdmg.js:391:8)
    at Pipeline._runStep (/opt/homebrew/lib/node_modules/create-dmg/node_modules/appdmg/lib/pipeline.js:46:10)
    at Pipeline._run (/opt/homebrew/lib/node_modules/create-dmg/node_modules/appdmg/lib/pipeline.js:94:10)
    at next (/opt/homebrew/lib/node_modules/create-dmg/node_modules/appdmg/lib/pipeline.js:35:25)
    at /opt/homebrew/lib/node_modules/create-dmg/node_modules/async/lib/async.js:52:16
    at done (/opt/homebrew/lib/node_modules/create-dmg/node_modules/async/lib/async.js:246:17)

Node.js v23.1.0
```

How can I solve this error?

**Comment by sindresorhus** [comment]
You have to report this on the `macos-alias` package.

**Comment by Jerry23011** [comment]
Hi, I'm wondering if there's a workaround for this error for now?
